blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸í•˜ê¸°
    url: https://github.com/SungbinYang/we-com-server/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ë…¼ì˜ê°€ í•„ìš”í•˜ë‹¤ë©´ Discussionì„ ì´ìš©í•˜ê±°ë‚˜ ì§ˆë¬¸ ë¼ë²¨ë¡œ ì´ìŠˆë¥¼ ë‚¨ê²¨ì£¼ì„¸ìš”.